[package]

name = "dbus"
version = "0.3.0"
authors = ["David Henningsson <diwic@ubuntu.com>"]

description = "Bindings to D-Bus, which is a bus commonly used on Linux for inter-process communication."
repository = "https://github.com/diwic/dbus-rs"
documentation = "http://diwic.github.io/dbus-rs-docs/dbus"
keywords = ["D-Bus", "DBus"]
license = "Apache-2.0/MIT"

[dependencies]
libc = "0.2"

[dev-dependencies]
tempdir = "0.3"
