[package]

name = "dbus"
version = "0.0.5"
authors = ["David Henningsson <diwic@ubuntu.com>"]

description = "D-Bus bindings"
repository = "https://github.com/diwic/dbus-rs"
keywords = ["D-Bus"]
license = "Apache-2.0/MIT"
